language: objective-c
osx_image: xcode7
#xcode_sdk: iphonesimulator9.0
#xcode_project: XWebView.xcodeproj
#xcode_scheme: XWebViewTests
#xctool_args: "-destination 'platform=iOS Simulator,OS=8.1,name=iPhone 5s'"
env:
  matrix:
    - OS=8.1
    - OS=9.0
script: xcodebuild -scheme XWebViewTests -configuration Debug -destination "platform=iOS Simulator,OS=$OS,name=iPhone 5s" test
